### ISSUE TITLE
Pasta "classes" inexistente no projeto

### ISSUE THREAD

**Issue by julianaconde** [ErickWendel/semana-javascript-expert08#5]
Olá, Erick!

Estou acompanhando o projeto, mas não encontrei a pasta **classes** que você cita no README.md. Quando clico no link para essa pasta, que está no arquivo README do projeto, aparece essa mensagem: 

![image](https://github.com/ErickWendel/semana-javascript-expert08/assets/29529757/a0001da8-909b-43a6-ace9-df7c403048d9)

Acredito que esteja faltando incluir essa pasta no projeto.

**Comment by ErickWendel** [comment]
Valeu! Corrigido!
